#!/usr/bin/env python3
"""Compare grasp quality metrics across all BimanBODex grasp types."""

from __future__ import annotations

import argparse
import json
import os
import sys
import warnings as py_warnings
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
from omegaconf import OmegaConf

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
SRC_DIR = REPO_ROOT / "src"
for import_path in (SCRIPT_DIR, SRC_DIR):
    if str(import_path) not in sys.path:
        sys.path.insert(0, str(import_path))

# `task.statistic` imports matplotlib for optional plots. A writable default keeps
# this pure CLI summary from emitting cache warnings on machines with read-only homes.
os.environ.setdefault("MPLCONFIGDIR", "/tmp/bimandex_matplotlib")

from process_all_grasp_types import GRASP_TYPE_NAMES, GRASP_TYPES, HAND_CONFIGS  # noqa: E402
from task.statistic import (  # noqa: E402
    DEFAULT_WRIST_APPROACH_AXIS,
    get_bimanual_relative_approach_geometry,
    get_bimanual_relative_approach_pairwise_distance,
    get_grasp_joint_pos_diversity,
    get_wrist_approach_pairwise_distance,
    get_wrist_tabletop_approach_coverage,
)

DEFAULT_TRANS_THRE = 0.05
DEFAULT_ANGLE_THRE = 15.0
DEFAULT_SELF_PENE_THRE = 0.0
DEFAULT_HAND_GEOM_DIST_THRE = 0.000
SEVERE_PENETRATION_SENTINEL = 100.0
FAILURE_REASON_NAMES = (
    "pregrasp_severe_penetration",
    "self_penetration",
    "self_geom_distance",
    "position_error",
    "rotation_error",
    "unknown",
)


@dataclass(frozen=True)
class StatJob:
    """Evaluation output location for one grasp type.

    Args:
        grasp_type: Canonical grasp type suffix, such as `right_two`.
        hand_name: Benchmark hand config name used for this grasp type.
        output_path: Root output folder generated by `process_all_grasp_types.py`.
        wrist_approach_axes: Per-hand local approach axes read from hand config.

    Returns:
        Dataclass instance describing one stat input folder.
    """

    grasp_type: str
    hand_name: str
    output_path: Path
    wrist_approach_axes: Any

    @property
    def eval_dir(self) -> Path:
        """Return the evaluation result directory.

        Args:
            None.

        Returns:
            Path to the folder containing evaluated `.npy` files.
        """

        return self.output_path / "evaluation"

    @property
    def succ_dir(self) -> Path:
        """Return the successful grasp directory.

        Args:
            None.

        Returns:
            Path to the folder containing successful grasp symlinks/files.
        """

        return self.output_path / "succgrasp"


@dataclass(frozen=True)
class EvalRecord:
    """Loaded evaluation sample with derived metadata.

    Args:
        scene_id: Scene identifier relative to the evaluation folder.
        success: Whether this grasp succeeded in simulation.
        data: Evaluation dictionary loaded from the `.npy` file.

    Returns:
        Dataclass instance used by the aggregate statistics.
    """

    scene_id: str
    success: bool
    data: dict[str, Any]


@dataclass(frozen=True)
class ObjectScaleStats:
    """Aggregated success statistics for one object scale.

    Args:
        scale_key: Stable printable scale key used in JSON output.
        evaluated_grasps: Number of evaluated grasps for this scale.
        successful_grasps: Number of successful grasps for this scale.

    Returns:
        Dataclass instance representing one object-scale row.
    """

    scale_key: str
    evaluated_grasps: int
    successful_grasps: int

    @property
    def success_rate(self) -> float | None:
        """Return grasp success rate for this scale.

        Args:
            None.

        Returns:
            Success rate, or None if no evaluated grasp exists.
        """

        if self.evaluated_grasps == 0:
            return None
        return float(self.successful_grasps / self.evaluated_grasps)


def build_parser() -> argparse.ArgumentParser:
    """Build the command line parser.

    Args:
        None.

    Returns:
        Configured `ArgumentParser` instance.
    """

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hand", choices=sorted(HAND_CONFIGS), required=True)
    parser.add_argument("--run-name", "--run_name", dest="run_name", required=True)
    parser.add_argument(
        "--save-root",
        "--save_root",
        dest="save_root",
        default="output",
        help="Root output folder used by process_all_grasp_types.py. Default: output.",
    )
    parser.add_argument(
        "--grasp-type",
        "--grasp_type",
        dest="grasp_types",
        choices=GRASP_TYPE_NAMES,
        action="append",
        help="Analyze only one grasp type. Repeat to select multiple. Default: all five grasp types.",
    )
    both_three_group = parser.add_mutually_exclusive_group()
    both_three_group.add_argument(
        "--include-both-three",
        "--include_both_three",
        dest="include_both_three",
        action="store_true",
        default=True,
        help="Include both_three in all statistics. This is the default.",
    )
    both_three_group.add_argument(
        "--exclude-both-three",
        "--exclude_both_three",
        dest="include_both_three",
        action="store_false",
        help="Exclude both_three before loading records, so all statistics ignore that grasp type.",
    )
    parser.add_argument(
        "--json-path",
        "--json_path",
        dest="json_path",
        default=None,
        help="Where to save the JSON summary. Default: <save_root>/<run>_<hand>_all_grasp_type_stats.json.",
    )
    parser.add_argument(
        "--trans-thre",
        "--trans_thre",
        dest="trans_thre",
        type=float,
        default=DEFAULT_TRANS_THRE,
        help=f"Translation threshold used to classify position-error failures. Default: {DEFAULT_TRANS_THRE}.",
    )
    parser.add_argument(
        "--angle-thre",
        "--angle_thre",
        dest="angle_thre",
        type=float,
        default=DEFAULT_ANGLE_THRE,
        help=f"Rotation threshold in degrees used to classify rotation-only failures. Default: {DEFAULT_ANGLE_THRE}.",
    )
    parser.add_argument(
        "--self-pene-thre",
        "--self_pene_thre",
        dest="self_pene_thre",
        type=float,
        default=DEFAULT_SELF_PENE_THRE,
        help=(
            "Deprecated compatibility option. Failure classification now always "
            "counts grasps with self_pene > 0 as self-penetration failures."
        ),
    )
    parser.add_argument(
        "--hand-geom-dist-thre",
        "--hand_geom_dist_thre",
        dest="hand_geom_dist_thre",
        type=float,
        default=DEFAULT_HAND_GEOM_DIST_THRE,
        help=(
            "Minimum allowed nearest hand-hand geom clearance in meters. Grasps "
            "with geom distance below this value are counted as failures. "
            f"Default: {DEFAULT_HAND_GEOM_DIST_THRE}."
        ),
    )
    parser.add_argument("--no-json", action="store_true", help="Print only; do not save a JSON summary.")
    return parser


def load_hand_wrist_approach_axes(hand_name: str) -> Any:
    """Load wrist approach axes from one benchmark hand config.

    Args:
        hand_name: Hand config name, such as `shadow` or `dual_dummy_arm_shadow`.

    Returns:
        Configured `wrist_approach_axes`, or the legacy default axis when the
        hand config does not define the field.
    """

    hand_config_path = REPO_ROOT / "config" / "hand" / f"{hand_name}.yaml"
    hand_config = OmegaConf.load(hand_config_path)
    approach_axes = hand_config.get("wrist_approach_axes")
    if approach_axes is None:
        return DEFAULT_WRIST_APPROACH_AXIS
    return OmegaConf.to_container(approach_axes, resolve=True)


def build_stat_jobs(
    hand_family: str,
    run_name: str,
    save_root: Path,
    grasp_types: list[str] | None,
    include_both_three: bool = True,
) -> list[StatJob]:
    """Create stat jobs with the same output naming as the all-type evaluation script.

    Args:
        hand_family: Hand family requested by CLI, one of `shadow` or `leap_sp`.
        run_name: Base run name used during evaluation.
        save_root: Root output folder containing per-type output folders.
        grasp_types: Optional selected grasp type names.
        include_both_three: Whether to keep `both_three` in the selected grasp
            types. When False, `both_three` is removed before any data is loaded.

    Returns:
        Ordered list of stat jobs.
    """

    selected_grasp_types = set(grasp_types or GRASP_TYPE_NAMES)
    if not include_both_three:
        selected_grasp_types.discard("both_three")
    hand_config = HAND_CONFIGS[hand_family]
    jobs = []
    for suffix, hand_kind, _tabletop_split in GRASP_TYPES:
        if suffix not in selected_grasp_types:
            continue
        hand_name = hand_config[f"{hand_kind}_hand"]
        output_path = save_root / f"{run_name}_{suffix}_{hand_name}"
        jobs.append(
            StatJob(
                grasp_type=suffix,
                hand_name=hand_name,
                output_path=output_path,
                wrist_approach_axes=load_hand_wrist_approach_axes(hand_name),
            )
        )
    return jobs


def scene_id_from_eval_path(eval_path: Path, eval_dir: Path) -> str:
    """Convert one evaluation file path into a scene identifier.

    Args:
        eval_path: Path to one evaluated grasp `.npy` file.
        eval_dir: Root evaluation folder for the grasp type.

    Returns:
        POSIX-style relative parent path, e.g. `object/tabletop_ur10e/scale_pose`.
    """

    return eval_path.relative_to(eval_dir).parent.as_posix()


def success_from_data(data: dict[str, Any], rel_path: Path, succ_rel_paths: set[str]) -> bool:
    """Read a simulation success flag with a filesystem fallback.

    Args:
        data: Evaluation dictionary loaded from an `.npy` file.
        rel_path: File path relative to the evaluation directory.
        succ_rel_paths: Relative paths found under the matching `succgrasp` directory.

    Returns:
        True if the evaluated grasp succeeded; otherwise False.
    """

    if "succ_flag" in data:
        return bool(np.asarray(data["succ_flag"]).item())
    return rel_path.as_posix() in succ_rel_paths


def has_self_collision(data: dict[str, Any]) -> bool:
    """Check whether one evaluated grasp has any hand-hand contact penetration.

    Args:
        data: Evaluation dictionary loaded from an `.npy` file.

    Returns:
        True if `self_pene` exists and is strictly greater than zero; otherwise
        False. Missing or non-finite values are not treated as self-penetration
        failures here so older/early-failed eval files fall back to other reasons.
    """

    self_pene = scalar_float_from_data(data, "self_pene")
    return self_pene is not None and self_pene > 0.0


def hand_geom_distance_from_data(data: dict[str, Any]) -> float | None:
    """Read nearest hand-hand geom clearance from one evaluation record.

    Args:
        data: Evaluation dictionary loaded from an `.npy` file.

    Returns:
        Non-negative nearest hand-hand geom clearance in meters if
        `self_signed_dist` is available and finite; otherwise None. The eval
        field uses penetration-positive signed distance, so clearance is the
        negated signed distance.
    """

    signed_dist = scalar_float_from_data(data, "self_signed_dist")
    if signed_dist is None:
        return None
    return -signed_dist


def has_too_close_hand_geoms(data: dict[str, Any], hand_geom_dist_thre: float) -> bool:
    """Check whether nearest hand-hand geom clearance is below threshold.

    Args:
        data: Evaluation dictionary loaded from an `.npy` file.
        hand_geom_dist_thre: Minimum allowed nearest hand-hand geom clearance in meters.

    Returns:
        True if the nearest hand-hand geom clearance exists and is smaller than
        `hand_geom_dist_thre`; otherwise False.
    """

    geom_distance = hand_geom_distance_from_data(data)
    return geom_distance is not None and geom_distance < hand_geom_dist_thre


def scalar_float_from_data(data: dict[str, Any], key: str) -> float | None:
    """Read one scalar float from an evaluation dictionary.

    Args:
        data: Evaluation dictionary loaded from an `.npy` file.
        key: Field name to read, such as `delta_pos` or `delta_angle`.

    Returns:
        Scalar float value if the field exists and contains one scalar; otherwise None.
    """

    if key not in data:
        return None
    value_array = np.asarray(data[key], dtype=np.float64)
    if value_array.size != 1:
        return None
    value = float(value_array.item())
    return value if np.isfinite(value) else None


def object_scale_key_from_data(data: dict[str, Any]) -> str:
    """Read a stable object-scale key from one evaluation dictionary.

    Args:
        data: Evaluation dictionary loaded from an `.npy` file.

    Returns:
        Printable object-scale key. Missing or invalid values are grouped as
        `unknown`.
    """

    scale_value = scalar_float_from_data(data, "obj_scale")
    if scale_value is None:
        return "unknown"
    return f"{scale_value:.6g}"


def object_scale_sort_key(scale_key: str) -> tuple[int, float | str]:
    """Build a stable sort key for object-scale summary rows.

    Args:
        scale_key: Printable object-scale key.

    Returns:
        Tuple that sorts numeric scales first and non-numeric keys last.
    """

    try:
        return (0, float(scale_key))
    except ValueError:
        return (1, scale_key)


def summarize_scalar_metric(records: list[EvalRecord], metric_key: str) -> dict[str, Any]:
    """Summarize one scalar metric over evaluation records.

    Args:
        records: Evaluation records to inspect.
        metric_key: Scalar metric field name, such as `qp_metric`.

    Returns:
        JSON-serializable metric statistics. `count` is the number of records
        with a finite scalar value for `metric_key`; aggregate values are None
        when no finite value exists.
    """

    values = [
        metric_value
        for record in records
        for metric_value in [scalar_float_from_data(record.data, metric_key)]
        if metric_value is not None
    ]
    if not values:
        return {
            "metric": metric_key,
            "count": 0,
            "mean": None,
            "std": None,
            "median": None,
            "min": None,
            "max": None,
        }

    value_array = np.asarray(values, dtype=np.float64)
    return {
        "metric": metric_key,
        "count": int(value_array.size),
        "mean": float(np.mean(value_array)),
        "std": float(np.std(value_array)),
        "median": float(np.median(value_array)),
        "min": float(np.min(value_array)),
        "max": float(np.max(value_array)),
    }


def classify_failure_reason(
    data: dict[str, Any],
    success: bool,
    trans_thre: float,
    angle_thre: float,
    hand_geom_dist_thre: float,
) -> str | None:
    """Classify one failed grasp into the main simulation failure reasons.

    Args:
        data: Evaluation dictionary loaded from an `.npy` file.
        success: Whether this grasp succeeded in simulation.
        trans_thre: Translation threshold used by evaluation success checks.
        angle_thre: Rotation threshold in degrees used by evaluation success checks.
        hand_geom_dist_thre: Minimum allowed nearest hand-hand geom clearance in meters.

    Returns:
        Failure reason key for failed grasps, None for successful grasps.
    """

    if success:
        return None

    delta_pos = scalar_float_from_data(data, "delta_pos")
    delta_angle = scalar_float_from_data(data, "delta_angle")
    if has_self_collision(data):
        return "self_penetration"
    if has_too_close_hand_geoms(data, hand_geom_dist_thre):
        return "self_geom_distance"

    # `_eval_simulate_under_extforce` records this sentinel when initial hand-object
    # or hand-hand penetration exceeds `task.simulation_metrics.max_pene`.
    if (
        delta_pos is not None
        and delta_angle is not None
        and delta_pos >= SEVERE_PENETRATION_SENTINEL
        and delta_angle >= SEVERE_PENETRATION_SENTINEL
    ):
        return "pregrasp_severe_penetration"

    if delta_pos is None or delta_angle is None:
        return "unknown"

    # Position failure is assigned before rotation because an object that was not
    # lifted/stabilized enough may also show a large final rotation.
    if delta_pos >= trans_thre:
        return "position_error"
    if delta_angle >= angle_thre:
        return "rotation_error"
    return "unknown"


def summarize_failure_reasons(
    records: list[EvalRecord],
    trans_thre: float,
    angle_thre: float,
    hand_geom_dist_thre: float,
) -> dict[str, Any]:
    """Summarize failure-reason counts and rates for one grasp type.

    Args:
        records: Loaded evaluation records for one grasp type.
        trans_thre: Translation threshold used to classify position-error failures.
        angle_thre: Rotation threshold in degrees used to classify rotation-only failures.
        hand_geom_dist_thre: Minimum allowed nearest hand-hand geom clearance in meters.

    Returns:
        JSON-serializable dictionary containing counts and ratios for each reason.
    """

    reason_counts = Counter()
    failed_count = 0
    for record in records:
        reason = classify_failure_reason(record.data, record.success, trans_thre, angle_thre, hand_geom_dist_thre)
        if reason is None:
            continue
        failed_count += 1
        reason_counts[reason] += 1

    evaluated_count = len(records)
    by_reason = {}
    for reason_name in FAILURE_REASON_NAMES:
        count = reason_counts.get(reason_name, 0)
        by_reason[reason_name] = {
            "count": int(count),
            "failed_percent": float(count / failed_count) if failed_count else None,
            "evaluated_percent": float(count / evaluated_count) if evaluated_count else None,
        }

    return {
        "failed_grasps": int(failed_count),
        "by_reason": by_reason,
    }


def load_eval_records(job: StatJob, hand_geom_dist_thre: float) -> tuple[list[EvalRecord], list[str]]:
    """Load all evaluation records for one grasp type.

    Args:
        job: Stat job describing one grasp type output folder.
        hand_geom_dist_thre: Minimum allowed nearest hand-hand geom clearance used
            to override the raw simulation success flag.

    Returns:
        Pair of loaded records and warning messages collected while reading.
    """

    warnings = []
    if not job.eval_dir.exists():
        return [], [f"{job.grasp_type}: missing evaluation directory: {job.eval_dir}"]

    eval_paths = sorted(job.eval_dir.rglob("*.npy"))
    if not eval_paths:
        return [], [f"{job.grasp_type}: no evaluation files found in {job.eval_dir}"]

    succ_rel_paths = set()
    if job.succ_dir.exists():
        succ_rel_paths = {path.relative_to(job.succ_dir).as_posix() for path in job.succ_dir.rglob("*.npy")}

    records = []
    for eval_path in eval_paths:
        rel_path = eval_path.relative_to(job.eval_dir)
        data = np.load(eval_path, allow_pickle=True).item()
        data["_source_path"] = str(eval_path)
        raw_success = success_from_data(data, rel_path, succ_rel_paths)
        success = (
            raw_success
            and not has_self_collision(data)
            and not has_too_close_hand_geoms(data, hand_geom_dist_thre)
        )
        records.append(
            EvalRecord(
                scene_id=scene_id_from_eval_path(eval_path, job.eval_dir),
                success=success,
                data=data,
            )
        )
    return records, warnings


def metric_value_is_finite(metric_value: Any) -> bool:
    """Check whether a diversity metric value contains only finite numbers.

    Args:
        metric_value: Metric result, usually a list or a JSON-serializable dictionary.

    Returns:
        True when all numeric leaves are finite; otherwise False.
    """

    if isinstance(metric_value, dict):
        return all(metric_value_is_finite(value) for value in metric_value.values())
    if isinstance(metric_value, (list, tuple)):
        return all(metric_value_is_finite(value) for value in metric_value)
    if isinstance(metric_value, (str, bool)) or metric_value is None:
        return True
    try:
        return bool(np.isfinite(float(metric_value)))
    except (TypeError, ValueError):
        return False


def safe_diversity(data_lst: list[dict[str, Any]], metric_name: str, metric_func) -> tuple[Any | None, str | None]:
    """Compute one diversity metric without aborting the whole summary.

    Args:
        data_lst: Evaluation dictionaries for one grasp type.
        metric_name: Human-readable metric name for warning text.
        metric_func: Callable that returns one JSON-serializable metric value.

    Returns:
        Pair of diversity value and warning message. The diversity value is None if the
        metric cannot be computed.
    """

    try:
        with py_warnings.catch_warnings():
            py_warnings.simplefilter("ignore", RuntimeWarning)
            metric_value = metric_func(data_lst)
        if not metric_value_is_finite(metric_value):
            return None, f"skip {metric_name}: metric returned non-finite values"
        return metric_value, None
    except (KeyError, ValueError) as error:
        return None, f"skip {metric_name}: {error}"


def build_wrist_pose_diversity(
    data_lst: list[dict[str, Any]],
    wrist_approach_axes: Any,
) -> tuple[dict[str, Any | None], list[str]]:
    """Compute wrist-pose diversity metrics for successful grasps.

    Args:
        data_lst: Successful evaluation dictionaries used for diversity.
        wrist_approach_axes: Per-hand local approach axes read from hand config.

    Returns:
        Pair of JSON-serializable wrist-pose diversity metrics and warning messages.
    """

    metrics: dict[str, Any | None] = {}
    warnings = []
    for metric_name, metric_func in (
        (
            "approach_coverage",
            lambda data_lst: get_wrist_tabletop_approach_coverage(
                data_lst,
                local_axes=wrist_approach_axes,
            ),
        ),
        (
            "approach_pairwise_distance",
            lambda data_lst: get_wrist_approach_pairwise_distance(
                data_lst,
                local_axes=wrist_approach_axes,
            ),
        ),
        ("joint_position_pca", get_grasp_joint_pos_diversity),
    ):
        metric_value, warning = safe_diversity(data_lst, f"wrist_pose.{metric_name}", metric_func)
        metrics[metric_name] = metric_value
        if warning:
            warnings.append(warning)
    return metrics, warnings


def build_bimanual_relative_approach_diversity(
    data_lst: list[dict[str, Any]],
    wrist_approach_axes: Any,
) -> tuple[dict[str, Any | None], list[str]]:
    """Compute bimanual relative approach diversity metrics.

    Args:
        data_lst: Successful evaluation dictionaries used for diversity.
        wrist_approach_axes: Per-hand local approach axes read from hand config.

    Returns:
        Pair of JSON-serializable bimanual relative approach metrics and warning
        messages.
    """

    metrics: dict[str, Any | None] = {
        "applicable": True,
        "metric_source": "left_wrist_approach_axis_in_right_wrist_frame_positive_hemisphere",
        "note": (
            "Left wrist approach axis is expressed in the right wrist local frame. "
            "Coverage is computed on the positive hemisphere defined by the right "
            "hand local palm-side approach axis."
        ),
    }
    warnings = []
    first_global_pose = np.asarray(data_lst[0].get("grasp_global_pose", []), dtype=np.float32)
    if first_global_pose.size // 7 < 2:
        metrics.update(
            {
                "applicable": False,
                "hemisphere_coverage": None,
                "hemisphere_pairwise_distance": None,
                "angle_coverage": None,
                "angle_pairwise_distance": None,
            }
        )
        return metrics, warnings

    for metric_name, metric_func in (
        (
            "hemisphere_coverage",
            lambda data_lst: get_bimanual_relative_approach_geometry(
                data_lst,
                local_axes=wrist_approach_axes,
            ),
        ),
        (
            "hemisphere_pairwise_distance",
            lambda data_lst: get_bimanual_relative_approach_pairwise_distance(
                data_lst,
                local_axes=wrist_approach_axes,
            ),
        ),
    ):
        metric_value, warning = safe_diversity(data_lst, f"bimanual_relative_approach.{metric_name}", metric_func)
        metrics[metric_name] = metric_value
        if warning:
            warnings.append(warning)
    # Backward-compatible aliases for older JSON consumers.
    metrics["angle_coverage"] = metrics.get("hemisphere_coverage")
    metrics["angle_pairwise_distance"] = metrics.get("hemisphere_pairwise_distance")
    return metrics, warnings


def summarize_grasp_type(
    job: StatJob,
    records: list[EvalRecord],
    trans_thre: float,
    angle_thre: float,
    hand_geom_dist_thre: float,
) -> dict[str, Any]:
    """Summarize grasp-level and diversity metrics for one grasp type.

    Args:
        job: Stat job describing the grasp type.
        records: Loaded evaluation records for this grasp type.
        trans_thre: Translation threshold used to classify position-error failures.
        angle_thre: Rotation threshold in degrees used to classify rotation-only failures.
        hand_geom_dist_thre: Minimum allowed nearest hand-hand geom clearance in meters.

    Returns:
        JSON-serializable summary dictionary.
    """

    success_count = sum(record.success for record in records)
    eval_count = len(records)
    scene_ids = {record.scene_id for record in records}
    success_scene_ids = {record.scene_id for record in records if record.success}
    diversity_records = [record for record in records if record.success]
    data_lst = [record.data for record in diversity_records]
    diversity: dict[str, Any | None] = {}
    warnings = []

    if len(data_lst) >= 2:
        wrist_pose_metrics, wrist_warnings = build_wrist_pose_diversity(data_lst, job.wrist_approach_axes)
        bimanual_relative_metrics, bimanual_warnings = build_bimanual_relative_approach_diversity(
            data_lst,
            job.wrist_approach_axes,
        )
        diversity = {
            "wrist_pose": wrist_pose_metrics,
            "bimanual_relative_approach": bimanual_relative_metrics,
            # Backward-compatible section name used by the previous script version.
            "bimanual_fingertip_angle": bimanual_relative_metrics,
            # Backward-compatible aliases used by older downstream notebooks.
            "wrist_tabletop_approach_coverage": wrist_pose_metrics.get("approach_coverage"),
            "wrist_approach_pairwise_distance": wrist_pose_metrics.get("approach_pairwise_distance"),
            "bimanual_relative_approach_geometry": bimanual_relative_metrics.get("hemisphere_coverage"),
            "bimanual_relative_approach_pairwise_distance": bimanual_relative_metrics.get("hemisphere_pairwise_distance"),
            "joint_position": wrist_pose_metrics.get("joint_position_pca"),
        }
        warnings.extend(wrist_warnings)
        warnings.extend(bimanual_warnings)
    else:
        warnings.append("skip diversity: fewer than two successful grasps")
        diversity = {
            "wrist_pose": {
                "approach_coverage": None,
                "approach_pairwise_distance": None,
                "joint_position_pca": None,
            },
            "bimanual_relative_approach": {
                "applicable": False,
                "metric_source": "left_wrist_approach_axis_in_right_wrist_frame_positive_hemisphere",
                "note": (
                    "Left wrist approach axis is expressed in the right wrist local frame. "
                    "Coverage is computed on the positive hemisphere defined by the right "
                    "hand local palm-side approach axis."
                ),
                "hemisphere_coverage": None,
                "hemisphere_pairwise_distance": None,
                "angle_coverage": None,
                "angle_pairwise_distance": None,
            },
            "bimanual_fingertip_angle": {
                "applicable": False,
                "metric_source": "left_wrist_approach_axis_in_right_wrist_frame_positive_hemisphere",
                "note": (
                    "Left wrist approach axis is expressed in the right wrist local frame. "
                    "Coverage is computed on the positive hemisphere defined by the right "
                    "hand local palm-side approach axis."
                ),
                "hemisphere_coverage": None,
                "hemisphere_pairwise_distance": None,
                "angle_coverage": None,
                "angle_pairwise_distance": None,
            },
            "wrist_tabletop_approach_coverage": None,
            "wrist_approach_pairwise_distance": None,
            "bimanual_relative_approach_geometry": None,
            "bimanual_relative_approach_pairwise_distance": None,
            "joint_position": None,
        }

    return {
        "grasp_type": job.grasp_type,
        "output_path": str(job.output_path),
        "evaluated_grasps": eval_count,
        "successful_grasps": int(success_count),
        "success_rate": float(success_count / eval_count) if eval_count else None,
        "qp_metric": summarize_scalar_metric(records, "qp_metric"),
        "qp_metric_success": summarize_scalar_metric(diversity_records, "qp_metric"),
        "failure_reasons": summarize_failure_reasons(records, trans_thre, angle_thre, hand_geom_dist_thre),
        "evaluated_scenes": len(scene_ids),
        "successful_scenes": len(success_scene_ids),
        "diversity_success_only": True,
        "diversity_grasps": len(data_lst),
        "diversity": diversity,
        "warnings": warnings,
    }


def summarize_scene_coverage(records_by_type: dict[str, list[EvalRecord]], grasp_type_num: int) -> dict[str, Any]:
    """Summarize how many successful grasp types each scene has.

    Args:
        records_by_type: Mapping from grasp type to loaded evaluation records.
        grasp_type_num: Number of grasp types included in this comparison.

    Returns:
        JSON-serializable scene coverage summary.
    """

    all_scene_ids = set()
    successful_types_by_scene: dict[str, set[str]] = defaultdict(set)
    for grasp_type, records in records_by_type.items():
        for record in records:
            all_scene_ids.add(record.scene_id)
            if record.success:
                successful_types_by_scene[record.scene_id].add(grasp_type)

    successful_type_count_by_scene = {
        scene_id: len(successful_types_by_scene.get(scene_id, set())) for scene_id in all_scene_ids
    }
    histogram = Counter(successful_type_count_by_scene.values())
    scene_num = len(all_scene_ids)
    distribution = {}
    for type_count in range(grasp_type_num + 1):
        count = histogram.get(type_count, 0)
        distribution[str(type_count)] = {
            "scene_count": int(count),
            "scene_percent": float(count / scene_num) if scene_num else None,
        }

    average_successful_type_num = (
        float(np.mean(list(successful_type_count_by_scene.values()))) if successful_type_count_by_scene else None
    )
    return {
        "evaluated_scenes": scene_num,
        "successful_scenes": int(sum(1 for type_count in successful_type_count_by_scene.values() if type_count > 0)),
        "scene_success_rate": (
            float(sum(1 for type_count in successful_type_count_by_scene.values() if type_count > 0) / scene_num)
            if scene_num
            else None
        ),
        "average_successful_grasp_type_num": average_successful_type_num,
        "successful_grasp_type_count_distribution": distribution,
    }


def summarize_object_scales(records_by_type: dict[str, list[EvalRecord]]) -> list[dict[str, Any]]:
    """Summarize evaluated/successful grasps and qp metrics by object scale.

    Args:
        records_by_type: Mapping from grasp type to loaded evaluation records.

    Returns:
        Ordered list of JSON-serializable object-scale statistics.
    """

    evaluated_counts = Counter()
    successful_counts = Counter()
    records_by_scale: dict[str, list[EvalRecord]] = defaultdict(list)
    successful_records_by_scale: dict[str, list[EvalRecord]] = defaultdict(list)
    for records in records_by_type.values():
        for record in records:
            scale_key = object_scale_key_from_data(record.data)
            evaluated_counts[scale_key] += 1
            records_by_scale[scale_key].append(record)
            if record.success:
                successful_counts[scale_key] += 1
                successful_records_by_scale[scale_key].append(record)

    scale_stats = []
    for scale_key in sorted(evaluated_counts, key=object_scale_sort_key):
        item = ObjectScaleStats(
            scale_key=scale_key,
            evaluated_grasps=int(evaluated_counts[scale_key]),
            successful_grasps=int(successful_counts[scale_key]),
        )
        scale_stats.append(
            {
                "object_scale": item.scale_key,
                "evaluated_grasps": item.evaluated_grasps,
                "successful_grasps": item.successful_grasps,
                "success_rate": item.success_rate,
                "qp_metric": summarize_scalar_metric(records_by_scale[scale_key], "qp_metric"),
                "qp_metric_success": summarize_scalar_metric(successful_records_by_scale[scale_key], "qp_metric"),
            }
        )
    return scale_stats


def build_metric_sections(
    per_type_summary: list[dict[str, Any]],
    object_scale_summary: list[dict[str, Any]],
    scene_coverage: dict[str, Any],
    total_eval: int,
    total_success: int,
) -> dict[str, Any]:
    """Organize metrics into plotting/table friendly JSON sections.

    Args:
        per_type_summary: Per-grasp-type summary dictionaries.
        object_scale_summary: Object-scale summary dictionaries.
        scene_coverage: Scene-level successful grasp-type coverage summary.
        total_eval: Total number of evaluated grasps across selected types.
        total_success: Total number of successful grasps across selected types.

    Returns:
        Dictionary with `data_counts`, `success_rates`, `diversity`, and
        `failure_reasons` sections.
    """

    per_type_counts = {
        item["grasp_type"]: {
            "evaluated_grasps": item["evaluated_grasps"],
            "successful_grasps": item["successful_grasps"],
        }
        for item in per_type_summary
    }
    per_type_sr = {
        item["grasp_type"]: item["success_rate"]
        for item in per_type_summary
    }
    per_type_qp_metric = {
        item["grasp_type"]: item["qp_metric"]
        for item in per_type_summary
    }
    per_type_qp_metric_success = {
        item["grasp_type"]: item["qp_metric_success"]
        for item in per_type_summary
    }
    per_scale_counts = {
        item["object_scale"]: {
            "evaluated_grasps": item["evaluated_grasps"],
            "successful_grasps": item["successful_grasps"],
        }
        for item in object_scale_summary
    }
    per_scale_sr = {
        item["object_scale"]: item["success_rate"]
        for item in object_scale_summary
    }
    per_scale_qp_metric = {
        item["object_scale"]: item["qp_metric"]
        for item in object_scale_summary
    }
    per_scale_qp_metric_success = {
        item["object_scale"]: item["qp_metric_success"]
        for item in object_scale_summary
    }
    per_type_diversity = {
        item["grasp_type"]: {
            "diversity_success_only": item["diversity_success_only"],
            "diversity_grasps": item["diversity_grasps"],
            "wrist_pose": item["diversity"]["wrist_pose"],
            "bimanual_relative_approach": item["diversity"]["bimanual_relative_approach"],
            "bimanual_fingertip_angle": item["diversity"]["bimanual_fingertip_angle"],
        }
        for item in per_type_summary
    }
    return {
        "data_counts": {
            "total_grasps": int(total_eval),
            "total_successful_grasps": int(total_success),
            "by_grasp_type": per_type_counts,
            "by_object_scale": per_scale_counts,
        },
        "success_rates": {
            "overall": float(total_success / total_eval) if total_eval else None,
            "scene": scene_coverage["scene_success_rate"],
            "by_grasp_type": per_type_sr,
            "by_object_scale": per_scale_sr,
        },
        "analytic_metrics": {
            "qp_metric": {
                "by_grasp_type": per_type_qp_metric,
                "by_object_scale": per_scale_qp_metric,
            },
            "qp_metric_success": {
                "by_grasp_type": per_type_qp_metric_success,
                "by_object_scale": per_scale_qp_metric_success,
            },
        },
        "diversity": {
            "success_only": True,
            "grasp_type_scene_coverage": {
                "average_successful_grasp_type_num": scene_coverage["average_successful_grasp_type_num"],
                "successful_grasp_type_count_distribution": scene_coverage[
                    "successful_grasp_type_count_distribution"
                ],
            },
            "by_grasp_type": per_type_diversity,
        },
        "failure_reasons": {
            "by_grasp_type": {
                item["grasp_type"]: item["failure_reasons"]
                for item in per_type_summary
            },
        },
    }


def format_rate(value: float | None) -> str:
    """Format a rate for terminal output.

    Args:
        value: Optional floating point rate.

    Returns:
        Percent string or `n/a`.
    """

    return "n/a" if value is None else f"{100.0 * value:.2f}%"


def format_diversity(value: list[float] | None) -> str:
    """Format a PCA diversity list for terminal output.

    Args:
        value: Optional list of cumulative explained variance ratios.

    Returns:
        Compact printable representation.
    """

    if value is None:
        return "n/a"
    return "[" + ", ".join(f"{item:.4f}" for item in value) + "]"


def format_metric(value: Any | None) -> str:
    """Format a diversity metric for terminal output.

    Args:
        value: Optional metric value. Lists are printed as compact numeric arrays;
            dictionaries print their most important coverage/statistic fields.

    Returns:
        Compact printable representation.
    """

    if value is None:
        return "n/a"
    if isinstance(value, list):
        return format_diversity(value)
    if isinstance(value, dict):
        if "pair_num" in value:
            unit = "deg" if value.get("distance_unit") == "degree" else value.get("distance_unit", "")
            pair_text = str(value["pair_num"])
            if value.get("estimated"):
                pair_text = f"{value['sampled_pair_num']}/{value['total_pair_num']}"
            return (
                f"mean={value['mean']:.2f}{unit}, std={value['std']:.2f}{unit}, "
                f"median={value['median']:.2f}{unit}, pairs={pair_text}"
            )
        if "coverage" in value:
            formatted = f"{100.0 * value['coverage']:.2f}%({value['occupied_bins']}/{value['total_bins']})"
            if "polar_coverage" in value:
                formatted += (
                    f", polar={100.0 * value['polar_coverage']:.2f}%"
                    f"({value['occupied_polar_bins']}/{value['total_polar_bins']})"
                )
            if "plane_angle_coverage" in value:
                formatted += (
                    f", angle={100.0 * value['plane_angle_coverage']:.2f}%"
                    f"({value['occupied_plane_angle_bins']}/{value['total_plane_angle_bins']})"
                )
            if "azimuth_coverage" in value:
                formatted += (
                    f", az={100.0 * value['azimuth_coverage']:.2f}%"
                    f"({value['occupied_azimuth_bins']}/{value['total_azimuth_bins']})"
                )
            if "below_table_percent" in value:
                formatted += f", below={100.0 * value['below_table_percent']:.2f}%"
            if "negative_hemisphere_percent" in value:
                formatted += f", neg={100.0 * value['negative_hemisphere_percent']:.2f}%"
            return formatted
        if "theta_coverage" in value:
            return (
                f"theta={value['theta_mean_deg']:.2f}+/-{value['theta_std_deg']:.2f}deg, "
                f"cov={100.0 * value['theta_coverage']:.2f}%({value['occupied_bins']}/{value['total_bins']})"
            )
    return str(value)


def format_scalar_metric_summary(metric_summary: dict[str, Any] | None) -> str:
    """Format scalar metric statistics for terminal output.

    Args:
        metric_summary: Summary generated by `summarize_scalar_metric`.

    Returns:
        Compact text with count, mean, and median, or `n/a` when unavailable.
    """

    if not metric_summary or metric_summary.get("count", 0) == 0:
        return "n/a"
    return (
        f"n={metric_summary['count']}, "
        f"mean={metric_summary['mean']:.4g}, "
        f"median={metric_summary['median']:.4g}"
    )


def format_failure_reasons(failure_reasons: dict[str, Any]) -> str:
    """Format failure reason percentages for terminal output.

    Args:
        failure_reasons: Failure-reason summary generated by `summarize_failure_reasons`.

    Returns:
        Compact string with percentages among failed grasps.
    """

    reason_labels = (
        ("pregrasp_severe_penetration", "pene"),
        ("self_penetration", "self"),
        ("self_geom_distance", "geom"),
        ("position_error", "pos"),
        ("rotation_error", "rot"),
        ("unknown", "unknown"),
    )
    reason_items = failure_reasons["by_reason"]
    return ", ".join(
        f"{label}={format_rate(reason_items[reason]['failed_percent'])}({reason_items[reason]['count']})"
        for reason, label in reason_labels
    )


def print_summary(summary: dict[str, Any]) -> None:
    """Print the aggregate summary in a readable table.

    Args:
        summary: JSON-serializable aggregate summary.

    Returns:
        None.
    """

    print(f"Hand: {summary['hand']}")
    print(f"Run name: {summary['run_name']}")
    print(f"Selected grasp types: {', '.join(summary['grasp_types'])}")
    print()
    print("Scene successful grasp-type coverage")
    scene_summary = summary["scene_coverage"]
    print(f"  evaluated scenes: {scene_summary['evaluated_scenes']}")
    print(f"  successful scenes: {scene_summary['successful_scenes']}")
    print(f"  scene success rate: {format_rate(scene_summary['scene_success_rate'])}")
    avg_type_num = scene_summary["average_successful_grasp_type_num"]
    print(f"  average successful grasp types per scene: {avg_type_num:.4f}" if avg_type_num is not None else "  average successful grasp types per scene: n/a")
    for type_count, item in scene_summary["successful_grasp_type_count_distribution"].items():
        print(f"  scenes with {type_count} successful grasp types: {item['scene_count']} ({format_rate(item['scene_percent'])})")
    print()
    print("Overall grasp success")
    print(f"  evaluated grasps: {summary['overall']['evaluated_grasps']}")
    print(f"  successful grasps: {summary['overall']['successful_grasps']}")
    print(f"  success rate: {format_rate(summary['overall']['success_rate'])}")
    print(
        "  failure classification thresholds: "
        f"trans<{summary['thresholds']['trans_thre']}, "
        f"angle<{summary['thresholds']['angle_thre']}, "
        f"self_pene<=0, "
        f"hand_geom_dist>={summary['thresholds']['hand_geom_dist_thre']}"
    )
    print(f"  diversity success only: {summary['diversity_success_only']}")
    print()
    print("Per grasp type")
    header = (
        "grasp_type",
        "eval",
        "succ",
        "succ_rate",
        "qp_metric",
        "qp_success",
        "failure_reasons",
        "scenes",
        "succ_scenes",
        "div_n",
        "approach_grid",
        "approach_pair",
        "rel_grid",
        "rel_pair",
        "joint_div",
    )
    print("  " + " | ".join(header))
    print("  " + " | ".join("-" * len(item) for item in header))
    for item in summary["per_grasp_type"]:
        diversity = item["diversity"]
        wrist_pose = diversity["wrist_pose"]
        bimanual_relative = diversity["bimanual_relative_approach"]
        row = (
            item["grasp_type"],
            str(item["evaluated_grasps"]),
            str(item["successful_grasps"]),
            format_rate(item["success_rate"]),
            format_scalar_metric_summary(item.get("qp_metric")),
            format_scalar_metric_summary(item.get("qp_metric_success")),
            format_failure_reasons(item["failure_reasons"]),
            str(item["evaluated_scenes"]),
            str(item["successful_scenes"]),
            str(item["diversity_grasps"]),
            format_metric(wrist_pose.get("approach_coverage")),
            format_metric(wrist_pose.get("approach_pairwise_distance")),
            format_metric(bimanual_relative.get("hemisphere_coverage")),
            format_metric(bimanual_relative.get("hemisphere_pairwise_distance")),
            format_metric(wrist_pose.get("joint_position_pca")),
        )
        print("  " + " | ".join(row))

    if summary["per_object_scale"]:
        print()
        print("Per object scale")
        header = ("object_scale", "eval", "succ", "succ_rate", "qp_metric", "qp_success")
        print("  " + " | ".join(header))
        print("  " + " | ".join("-" * len(item) for item in header))
        for item in summary["per_object_scale"]:
            row = (
                item["object_scale"],
                str(item["evaluated_grasps"]),
                str(item["successful_grasps"]),
                format_rate(item["success_rate"]),
                format_scalar_metric_summary(item.get("qp_metric")),
                format_scalar_metric_summary(item.get("qp_metric_success")),
            )
            print("  " + " | ".join(row))

    warnings = summary["warnings"] + [
        f"{item['grasp_type']}: {warning}"
        for item in summary["per_grasp_type"]
        for warning in item["warnings"]
    ]
    if warnings:
        print()
        print("Warnings")
        for warning in warnings:
            print(f"  {warning}")


def build_summary(args: argparse.Namespace) -> dict[str, Any]:
    """Build the full all-grasp-type comparison summary.

    Args:
        args: Parsed command line arguments.

    Returns:
        JSON-serializable aggregate summary.
    """

    jobs = build_stat_jobs(
        args.hand,
        args.run_name,
        Path(args.save_root),
        args.grasp_types,
        include_both_three=args.include_both_three,
    )
    records_by_type = {}
    per_type_summary = []
    warnings = []

    for job in jobs:
        records, job_warnings = load_eval_records(job, args.hand_geom_dist_thre)
        records_by_type[job.grasp_type] = records
        warnings.extend(job_warnings)
        per_type_summary.append(
            summarize_grasp_type(
                job,
                records,
                args.trans_thre,
                args.angle_thre,
                args.hand_geom_dist_thre,
            )
        )

    total_eval = sum(item["evaluated_grasps"] for item in per_type_summary)
    total_success = sum(item["successful_grasps"] for item in per_type_summary)
    scene_coverage = summarize_scene_coverage(records_by_type, len(jobs))
    object_scale_summary = summarize_object_scales(records_by_type)
    metric_sections = build_metric_sections(
        per_type_summary,
        object_scale_summary,
        scene_coverage,
        total_eval,
        total_success,
    )
    return {
        "hand": args.hand,
        "run_name": args.run_name,
        "save_root": args.save_root,
        "grasp_types": [job.grasp_type for job in jobs],
        "include_both_three": bool(args.include_both_three),
        "thresholds": {
            "trans_thre": float(args.trans_thre),
            "angle_thre": float(args.angle_thre),
            "self_pene_thre": 0.0,
            "hand_geom_dist_thre": float(args.hand_geom_dist_thre),
        },
        "diversity_success_only": True,
        "data_counts": metric_sections["data_counts"],
        "success_rates": metric_sections["success_rates"],
        "analytic_metrics": metric_sections["analytic_metrics"],
        "diversity": metric_sections["diversity"],
        "failure_reasons": metric_sections["failure_reasons"],
        "scene_coverage": scene_coverage,
        "overall": {
            "evaluated_grasps": int(total_eval),
            "successful_grasps": int(total_success),
            "success_rate": float(total_success / total_eval) if total_eval else None,
        },
        "per_object_scale": object_scale_summary,
        "per_grasp_type": per_type_summary,
        "warnings": warnings,
    }


def save_json_summary(summary: dict[str, Any], json_path: Path) -> None:
    """Save the aggregate summary as formatted JSON.

    Args:
        summary: JSON-serializable aggregate summary.
        json_path: Output JSON path.

    Returns:
        None.
    """

    json_path.parent.mkdir(parents=True, exist_ok=True)
    with json_path.open("w", encoding="utf-8") as file:
        json.dump(summary, file, indent=2)
        file.write("\n")


def main(argv: list[str] | None = None) -> int:
    """Run the all-grasp-type statistic script.

    Args:
        argv: Optional argument list for tests; None uses `sys.argv`.

    Returns:
        Process exit code.
    """

    parser = build_parser()
    args = parser.parse_args(argv)
    summary = build_summary(args)
    print_summary(summary)

    if summary["overall"]["evaluated_grasps"] == 0:
        print("No evaluated grasps found for the selected run.", file=sys.stderr)
        return 1

    if not args.no_json:
        json_path = Path(args.json_path) if args.json_path else Path(args.save_root) / f"{args.run_name}_{args.hand}_all_grasp_type_stats.json"
        save_json_summary(summary, json_path)
        print()
        print(f"Saved JSON summary: {json_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
